### ISSUE TITLE
Exporting challenges not working

### ISSUE THREAD

**Issue by Ret2lib** [CTFd/CTFd#995] opened 2019-05-14 05:43 UTC
**Environment**:

  - CTFd Version/Commit: 2.1.1
  - Operating System: Ubuntu
  - Web Browser and Version: Chrome/Firefox

**What happened?** Challenges.json and flag.json is empty when exporting backup

**What did you expect to happen?** It should contain the flags and challenges

**How to reproduce your issue** Pull latest commit, run in docker, create a challenge and export it.

**Any associated stack traces or error logs**

**Comment by ColdHeat** [comment] 2019-05-14 05:45
Are you properly accessing the docker container and exporting from inside the container?

**Comment by ColdHeat** [comment] 2019-05-14 05:48
Exports are covered by a test case: https://github.com/CTFd/CTFd/blob/49b48a9e5319297baff84b32c3c814fe722b5bf1/tests/utils/test_exports.py

Can you reproduce this without docker?

**Comment by ColdHeat** [comment] 2019-05-18 23:48
I'm going to close this. If you're able to provide a minimal test case or find the root cause I can re-open.

**Closed by ColdHeat** 2019-05-18 23:48 UTC
