### ISSUE TITLE
Notifications not showing up in admin page until after page refresh

### ISSUE THREAD

**Issue by jimender2** [CTFd/CTFd#1651] opened 2020-09-15 22:30 UTC
CTFd 3.1.0

When I hit the button to create a new notification, it sends it off successfully but you do not see it appear in the admin page until after you refresh the page. This action caused one of my admins to send a notification 3 times because they did not see it appear.

**Comment by ColdHeat** [comment] 2020-09-16 00:08
Maybe a duplicate of #1641 if they had multiple CTFd tabs open.

**Comment by jimender2** [comment] 2020-09-16 00:56
I am more talking about this page.
![image](https://user-images.githubusercontent.com/35303639/93278214-0d617c80-f792-11ea-933e-28ab6171c26a.png)

These notifications are not updating when I hit the submit.  I think that when you hit the submit button, it should refresh the notification contents to fix this.

**Comment by ColdHeat** [comment] 2020-09-16 23:00
Ah okay, normally people don't retry notification submission b/c they see the notification pop up for them. Sometimes you might not get the notification on your current tab which is the problem that the other issue is tracking. 

Refresh could be done but I'm not sure if it makes more sense than the popup. 

It would be good to know if your admin saw a pop up and tried to retry anyway or if he didn't see a popup/alert.

**Comment by jimender2** [comment] 2020-09-16 23:30
I do not believe that they saw the popup.  They were in a kinda frantic rush trying to get the notification out and did not see it pop up.
Could we also get the notification form cleared out on submission?  Right now it appears that the text and title stay in the notification form once it submits.

**Comment by ColdHeat** [comment] 2020-09-17 06:38
I think refreshing after notification send and clearing out the inputs is relatively simple to do. PR welcome if you're interested. Here's the relevant JS file: https://github.com/CTFd/CTFd/blob/master/CTFd/themes/admin/assets/js/pages/notifications.js.

**Closed** 2020-09-20 07:05 UTC
