### ISSUE TITLE
Add a test box for regex flags or other flag types

### ISSUE THREAD

**Issue by doegox** [CTFd/CTFd#391] opened 2017-09-16 22:03 UTC
Hi
Just a little suggestion: when choosing to configure a flag with a regex it would be convenient to have a small test text box where one can type a flag candidate and see if it's validated by the regex or not.
Otherwise there is always some doubt (as there are several slight syntax differences between regex engines) and it's not convenient to flag with a test account, remove flag from admin, flag again etc.

**Comment by ColdHeat** [comment] 2017-11-30 23:26
I think a simpler way to think about this is that admins should be able to preview a challenge from the admin panel so I've renamed it as such.

**Comment by ColdHeat** [comment] 2017-12-05 08:22
In version 1.1 there will be a challenge preview. Using this you can test your flags after you've added them in. 

I realize this is not exactly what the issue is but I feel this is a generic solution that helps regardless of key type.

![image](https://user-images.githubusercontent.com/166333/33596813-298c7ac4-d96b-11e7-82fd-61b218c9d245.png)

I'm not going to close this because the issue isn't particularly resolved, but I'm going to remove this from the milestone and leave this up to the community to hopefully implement and PR in.

**Comment by doegox** [comment] 2017-12-05 08:46
It sounds already nice! Thanks.

**Comment by ColdHeat** [comment] 2019-04-07 18:21
Challenge preview works well from my perspective so I'm going to close this.

**Closed by ColdHeat** 2019-04-07 18:21 UTC
Labels: enhancement
