### ISSUE TITLE
Pause/freeze not working

### ISSUE THREAD

**Issue by cool00geek** [CTFd/CTFd#1937] opened 2021-07-02 16:45 UTC
Neither the pause nor freeze functionality is working even on a fresh CTFd instance without any questions or users other than the admin. 

Pausing the CTF gives the following error: ![image](https://user-images.githubusercontent.com/16456478/124305634-39c86880-db1a-11eb-9b55-c6a47b4a5c02.png)

And freezing gives the following: ![image](https://user-images.githubusercontent.com/16456478/124305655-3fbe4980-db1a-11eb-8ec3-b2db9ccc1f34.png)

**Comment by ColdHeat** [comment] 2021-07-03 04:46
Duplicate of #1928. This should have been fixed by #1931. Try pulling the latest copy of the repo.

**Closed by ColdHeat** 2021-07-03 04:46 UTC
