### ISSUE TITLE
Backup Export return 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Colbert337** [CTFd/CTFd#296] opened 2017-06-21 09:05 UTC
Dear ColdHeat,

hello

 admin-config-backup-export,return 500 (Internal Server Error)

the request is http://xxx/admin/export?segments=challenges,teams,both,metadata

2017-06-21 16:54:16 [533] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 129, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 326, in write_file
    fileno = respiter.filelike.fileno()
UnsupportedOperation: fileno

how can i fix it? thanks you !

**Comment by ColdHeat** [comment] 2017-06-21 15:45
I will need a larger stack trace to debug this since exports work for me.

**Comment by Colbert337** [comment] 2017-06-23 04:37
I don't know why. when  I restart gunicorn , exports work for me.
thanks !

**Comment by Colbert337** [comment] 2017-06-27 08:17
The problem arises again.

```
2017-06-27 16:12:54 [30145] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 129, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/dist-packages/gunicorn/http/wsgi.py", line 326, in write_file
    fileno = respiter.filelike.fileno()
UnsupportedOperation: fileno
```
the gunicorn version is 19.7.1

```
ubuntu@VM-ubuntu:/var/www/CTFd/CTFd$ gunicorn -v
gunicorn (version 19.7.1)
```

**Comment by ColdHeat** [comment] 2017-06-28 01:10
I don't think I'll be able to reproduce this without getting a a database dump from your database. Would you be able to provide that? I can give you an email address to send it to if you'd like.

**Comment by Colbert337** [comment] 2017-06-28 13:21
@ColdHeat my email is 784392466@qq.com

**Comment by ColdHeat** [comment] 2017-09-04 10:22
Closing since I never got a database dump.

**Closed by ColdHeat** 2017-09-04 10:22 UTC
